### PR TITLE
[WIP] Add oni.vn

### PR DESCRIPTION
**Pull request by thangngoc89**
It seems easy at first. I even can get the real url in browser's console log. But I can't make it work at all.

@matteocontrini could you help me with this?

### CODE REVIEW

**Comment by matteocontrini** [comment]
I'll check later

**Comment by matteocontrini** [comment]
I don't understand anything about the language of that website, but I can find this line in the source code:

``` html
<meta property="og:url" content="http://github.com" />  
```

That should be enough

**Comment by thangngoc89** [comment]
@matteocontrini You're awesome. How can I even miss that.

By the way, my attemp is sending a get request (which is available in source code).

You can paste this function into browser's console.log and it'll show you the real url

``` javascript
$.ajax({
                   type: "GET",
                    url: domain+"click.html",
                    data:"code=TWjx7&token=9aae77ac6f9d7d8ba79d380efb87d409&q=0",
                    contentType: "application/json; charset=utf-8",

                    success: function (html) {
                        //alert(html);
                        window.location = html;
                    }
                })     
```

But can't make it work in node

**Comment by matteocontrini** [comment]
Sometimes there are server-side checks for the User-Agent or headers that only browsers add to requests.

**Comment by thangngoc89** [comment]
Ya. These oni.vn guys are good

**Comment by thangngoc89** [comment]
Rebased and added via https://github.com/matteocontrini/node-bypasser/commit/dac430e9418a0fdf5b0e47f303aa1a58f4b155c6

**Pull request closed without merging**
